# App runs on host machine; local Postgres container is exposed to localhost:5433
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_local
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

security.jwt.secret=BicRz58vuViRALcSlUn5CcNLjgvoENYHHurwah6IhGQ
