services:
  frontend:
    labels:
      traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.https-redirect.redirectscheme.permanent: "true"
      traefik.http.routers.domain-http.entrypoints: web
      traefik.http.routers.domain-http.rule: Host(`${APP_HOST}`) || Host(`www.${APP_HOST}`)
      traefik.http.routers.domain-http.priority: "1000"
      traefik.http.routers.domain-http.middlewares: https-redirect
      traefik.http.routers.frontend-https.entrypoints: websecure
      traefik.http.routers.frontend-https.rule: (Host(`${APP_HOST}`) || Host(`www.${APP_HOST}`)) && PathPrefix(`/`)
      traefik.http.routers.frontend-https.priority: "1"
      traefik.http.routers.frontend-https.tls: "true"
      traefik.http.routers.frontend-https.tls.certresolver: letsencrypt
      traefik.http.routers.frontend-https.service: frontend

  auth-service:
    labels:
      traefik.http.routers.auth-legacy-https.entrypoints: websecure
      traefik.http.routers.auth-legacy-https.rule: (Host(`${APP_HOST}`) || Host(`www.${APP_HOST}`)) && (PathPrefix(`/me`) || PathPrefix(`/users`) || PathPrefix(`/businesses`) || PathPrefix(`/invitations`) || (Path(`/login`) && Method(`POST`)) || (Path(`/register`) && Method(`POST`)))
      traefik.http.routers.auth-legacy-https.priority: "300"
      traefik.http.routers.auth-legacy-https.tls: "true"
      traefik.http.routers.auth-legacy-https.tls.certresolver: letsencrypt
      traefik.http.routers.auth-legacy-https.service: auth

  fleet-service:
    labels:
      traefik.http.routers.fleet-legacy-https.entrypoints: websecure
      traefik.http.routers.fleet-legacy-https.rule: (Host(`${APP_HOST}`) || Host(`www.${APP_HOST}`)) && PathPrefix(`/vehicles`)
      traefik.http.routers.fleet-legacy-https.priority: "300"
      traefik.http.routers.fleet-legacy-https.tls: "true"
      traefik.http.routers.fleet-legacy-https.tls.certresolver: letsencrypt
      traefik.http.routers.fleet-legacy-https.service: fleet

  document-service:
    labels:
      traefik.http.routers.documents-legacy-https.entrypoints: websecure
      traefik.http.routers.documents-legacy-https.rule: (Host(`${APP_HOST}`) || Host(`www.${APP_HOST}`)) && (PathPrefix(`/history`) || PathPrefix(`/alerts`) || PathPrefix(`/reports`) || PathPrefix(`/unread-count`) || PathPrefix(`/notifications`))
      traefik.http.routers.documents-legacy-https.priority: "300"
      traefik.http.routers.documents-legacy-https.tls: "true"
      traefik.http.routers.documents-legacy-https.tls.certresolver: letsencrypt
      traefik.http.routers.documents-legacy-https.service: documents
