spring.application.name=fleet-service
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
security.jwt.secret=${JWT_SECRET:01234567890123456789012345678901}
vehicle.image.storage.path=${VEHICLE_IMAGE_STORAGE_PATH:./vehicle-images}
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost,http://localhost:5173}
springdoc.swagger-ui.url=/api/fleet/v3/api-docs
springdoc.swagger-ui.config-url=/api/fleet/v3/api-docs/swagger-config
springdoc.swagger-ui.oauth2-redirect-url=/api/fleet/swagger-ui/oauth2-redirect.html
