package com.fleet.parser.dto;

public enum ParserErrorCode {
    INVALID_REQUEST,
    UNSUPPORTED_FILE_TYPE,
    TEXT_EXTRACTION_FAILED,
    OCR_FAILED,
    DOCUMENT_TYPE_DETECTION_FAILED,
    OLLAMA_UNAVAILABLE,
    OLLAMA_TIMEOUT,
    OLLAMA_INVALID_RESPONSE,
    EXTRACTION_VALIDATION_FAILED,
    INTERNAL_ERROR
}
