global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  http:
    address: ":80"
  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: false

providers:
  file:
    filename: /dynamic_conf.yml
    watch: true

log:
  level: INFO

accessLog: {}
